services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: example_app
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5435:5432"

# docker-compose -f docker-compose.test.yml up -d --remove-orphans
# docker-compose -f docker-compose.test.yml down
